"""Authentication

Revision ID: d56e15fd6704
Revises: 
Create Date: 2025-04-29 13:47:29.527923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.users import Role, Gender

# revision identifiers, used by Alembic.
revision: str = 'd56e15fd6704'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_enum = sa.Enum(*[role for role in Role], name='role')
gender_enum = sa.Enum(*[gender for gender in Gender], name='gender')


def upgrade() -> None:
    """Upgrade schema."""
    user_enum.create(op.get_bind(), checkfirst=True)
    gender_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column("users", sa.Column("role", user_enum, nullable=False))
    op.add_column("users", sa.Column("gender", gender_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    sa.Enum(name="role").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="gender").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
